[build]
  command = "yarn run build"
  publish = "dist"
  NODE_ENV = "8.9.0"

[context.branch-deploy]
  command = "yarn run build"
  publish = "dist"
  NODE_ENV = "8.9.0"


# Look after the old use of journal in urls
[[redirects]]
  from = "/tag/*"
  to = "/tags/#:splat"
  status = 302
