[build]
  command = "yarn run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "8.9.0"

# arrange tag listings on one page, but look after people who hack the URL
[[redirects]]
  from = "/tag/*"
  to = "/tags/#:splat"
  status = 302
